version: 2.1

commands:
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/code-hybrid-flow
          paths:
            - .
  restore_workspace:
    steps:
      - attach_workspace:
          at: ~/code-hybrid-flow
  restore_gradle:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "sdk/build.gradle.kts" }}-{{ checksum "service/build.gradle.kts" }}
  save_gradle:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "sdk/build.gradle.kts" }}-{{ checksum "service/build.gradle.kts" }}
          paths:
            - ~/.gradle/caches

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/redis:5.0.4-alpine3.9
      - image: rabbitmq:3.7
    environment:
      - RABBIT_PORT: 5672
      - REDIS_PORT: 6379
    working_directory: ~/code-hybrid-flow
    steps:
      - checkout
      - restore_gradle
      - run: ./gradlew test jacocoTestReport build
      - codecov/upload:
          file: service/build/reports/jacoco/test/jacocoTestReport.xml
          flags: service
      - run: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            APPENDIX=""
          elif [ "$CIRCLE_BRANCH" == "development" ]; then
            APPENDIX="-SNAPSHOT"
          else
            APPENDIX="-${CIRCLE_SHA1}"
          fi
          echo $(./gradlew properties -q | grep "^version:" | awk '{print $2}')$APPENDIX > build/current_version
          echo "current version is: "
          cat build/current_version
      - save_gradle
      - save_workspace
  publish_sdk:
    docker:
      - image: circleci/openjdk:8u181-jdk
    working_directory: ~/code-hybrid-flow
    steps:
      - restore_workspace
      - restore_gradle
      - run: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            ./gradlew :code-hybrid-flow-sdk:publishSdkPublicationToReleaseRepository
          else
            ./gradlew :code-hybrid-flow-sdk:publishSdkPublicationToSnapshotRepository
          fi
  publish_image:
    docker:
      - image: docker:18.09.5
    working_directory: ~/code-hybrid-flow
    steps:
      - setup_remote_docker
      - restore_workspace
      - run: |
          unset CURRENT_VERSION
          CURRENT_VERSION=$(cat build/current_version)
          cd service
          docker build -t imulab/q-code-hybrid-service:${CURRENT_VERSION} .
          echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
          docker push imulab/q-code-hybrid-service:${CURRENT_VERSION}

workflows:
  version: 2.1
  dev:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - publish_sdk:
          requires:
            - build
      - publish_image:
          requires:
            - build
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - build
      - publish_sdk:
          requires:
            - hold
      - publish_image:
          requires:
            - hold